### ISSUE TITLE
Installing the package fails due to missing powershell cmdlets

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.Host#68]
Taskforce: @andreasohlund, @weralabaj @bording @SeanFeldman 

### POA

- [x] Merge the [pull](https://github.com/Particular/NServiceBus.Host/issues/71)
- [x] Update to latest core to get samples working (#75) 
- [x] Merge #76 to prevent silent overwriting of an existing EndpointConfig.cs when upgrading
- [x] Smoke test an upgrade + a fresh install
- [x] Get confirmation from docs maintainers that no other doco needs to be changed

Doco & samples:
- [x] Add section to upgrade guide (https://github.com/Particular/NServiceBus.Host/issues/68#issuecomment-205811920) PR https://github.com/Particular/docs.particular.net/pull/1388
- [x] Review http://docs.particular.net/nservicebus/hosting/nservicebus-host/  and 
http://docs.particular.net/nservicebus/operations/installers, make sure it's accurate.
- [x] Update and smoke test the snippets https://github.com/Particular/docs.particular.net/pull/1388
- [x] Update and smoke test the host samples https://github.com/Particular/docs.particular.net/pull/1388
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/nservicebus-host/Version_6
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostcustom/Version_6
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostdefault/Version_6
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostprofiles/Version_6
- [x] Smoke test manual upgrade from V5 to V6
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/nservicebus-host/Version_5
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostcustom/Version_5
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostdefault/Version_5
   - [x] https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostprofiles/Version_5

### Exception
I tried to upgrade a Host based project from CoreV5 to CoreV6 using packages from MyGet, the Host upgrade (using `7.0.0-unstable0068`) fails with the following error:

```
Executing script file 'C:\Repos\mauroservienti\NServiceBus.Samples\v6\packages\NServiceBus.Host.7.0.0-unstable0068\tools\install.ps1'...


IsDirty              : False
FileCount            : 1
Name                 : EndpointConfig.cs
Collection           : System.__ComObject
Properties           : System.__ComObject
DTE                  : System.__ComObject
Kind                 : {6BB5F8EE-4483-11D3-8BCF-00C04F8EC28C}
ProjectItems         : System.__ComObject
Object               : System.__ComObject
ExtenderNames        : {}
ExtenderCATID        : {610D4615-D0D5-11D2-8599-006097C68E81}
Saved                : True
ConfigurationManager : 
FileCodeModel        : System.__ComObject
Document             : 
SubProject           : 
ContainingProject    : System.__ComObject

Add-NServiceBusMessageForwardingInCaseOfFaultConfig : The term 'Add-NServiceBusMessageForwardingInCaseOfFaultConfig' 
is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At C:\Repos\mauroservienti\NServiceBus.Samples\v6\packages\NServiceBus.Host.7.0.0-unstable0068\tools\install.ps1:99 
char:2
+     Add-NServiceBusMessageForwardingInCaseOfFaultConfig $project.Name
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : ObjectNotFound: (Add-NServiceBus...seOfFaultConfig:String) [], CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException

Add-NServiceBusUnicastBusConfig : The term 'Add-NServiceBusUnicastBusConfig' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At C:\Repos\mauroservienti\NServiceBus.Samples\v6\packages\NServiceBus.Host.7.0.0-unstable0068\tools\install.ps1:100 
char:2
+     Add-NServiceBusUnicastBusConfig $project.Name
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : ObjectNotFound: (Add-NServiceBusUnicastBusConfig:String) [], CommandNotFoundException
   + FullyQualifiedErrorId : CommandNotFoundException
```

To complicate things the error causes the `EndpointConfig.cs` file to be empty, deleting all my previous configurations.

**Comment by SimonCropp** [comment]
the powershell helpers were removed as part of v6 http://docs.particular.net/nservicebus/upgrades/5to6#visual-studio-powershell-helpers-removed

so either they need to be ported to the host, or stop hacking the config file

**Comment by andreasohlund** [comment]
I propose we stop hacking the file?

**Comment by andreasohlund** [comment]
@Particular/platform-dev-squad realizing that this is a blocker for beta since this prevents the host to be installed. I propose that we move it into in-progress asap?

**Comment by andreasohlund** [comment]
@Particular/docs-maintainers looking at http://docs.particular.net/nservicebus/hosting/windows-service it seems that we're not specifying the error queue in code do we need to add that?

are there other doco that we need to update? (the ps cmdlets are already mentioned in the upgrade guide)

**Comment by andreasohlund** [comment]
Perhaps a section for the host "Error and audit queues are no longer specified via the app.config when creating a new endpoint using the NServiceBus.Host package" ?

**Comment by andreasohlund** [comment]
>To complicate things the error causes the EndpointConfig.cs file to be empty, deleting all my previous configurations.

Note that this can still happen for other reasons but I propose we deal with that separately since that behavior has always existed

**Comment by andreasohlund** [comment]
@SimonCropp added you to the taskforce to review the doco changed and help @weralabaj out if needed.

**Comment by bording** [comment]
Adding myself to the task force per @andreasohlund's invitation.

**Comment by bording** [comment]
Using `NServiceBus.Host 7.0.0-unstable0081` and `NServiceBus.Host32 7.0.0-unstable0081` packages I have tested both installing it into a new project and upgrading projects using version 6.0.0 of the host and everything appears to be working correctly.

**Comment by SimonCropp** [comment]
@bording i tried and the host overwrote all my config in the .cs file

**Comment by andreasohlund** [comment]
Does it repro consitently?

**Comment by bording** [comment]
@SimonCropp I noticed that it did that, so I went and tested a Host 4.7.12 -> 6.0.0 upgrade, and the same thing happened.

I noticed that the `install.ps1` has some logic in there to attempt to prevent an overwrite when the file already exists, but it doesn't appear to be working.

However, I'm not sure that's actually a bad thing, since when upgrading we'd want to bring in the new code-based config values included in the new file.

**Comment by andreasohlund** [comment]
Does a v4 to v5 upgrade overwrite as well? If not what is different?

**Comment by andreasohlund** [comment]
Overwriting is IMO a no go. Should we raise s different issue for that?

**Comment by bording** [comment]
> Does a v4 to v5 upgrade overwrite as well? If not what is different?

V4 and V5 of what? The upgrade I tested went from core 4.7.12 to 5.2.14

Or are you wanting to know about V5 of the Host?

**Comment by SeanFeldman** [comment]
Waffle has unassigned the original owner of the issue just because PR connected to the issue had myself as the assignee :disappointed:

**Comment by andreasohlund** [comment]
Yea, talking about a host upgrade to figure out if this is a new issue or if it existed in older versions

**Comment by bording** [comment]
> Yea, talking about a host upgrade to figure out if this is a new issue or if it existed in older versions

Right, and I did that. It has the same behavior.

**Comment by SimonCropp** [comment]
yes it is reproducible

**Comment by SimonCropp** [comment]
i say we bite the bullet and remove the endpointconfig injection. it has always been buggy and i see too many edge cases that will make it fail

**Comment by SeanFeldman** [comment]
@SimonCropp and let the obsolete messages drive users toward the right implementations? That's ok for upgrades. But what about new projects? What if `EndpointConfig.cs` is not created by powershell, but is a part of the nuget package as a content file?

**Comment by SimonCropp** [comment]
> What if EndpointConfig.cs is not created by powershell, but is a part of the nuget package as a content file?

this also fails since for many projects people move the endpoint config to some other common lib. they also ref the host nuget from multiple locations. eg from a lib that wants to use the extension points in the host. in all of these scenarios the host fails and injects bad code

**Comment by SeanFeldman** [comment]
That sounds like a case with advanced users that will be able to remove `endpointconfig.cs`.
Questions is: should we sacrifice experience for those that are not advanced users if advanced users can resolve an issue of injected file.

**Comment by SimonCropp** [comment]
> That sounds like a case with advanced users that will be able to remove endpointconfig.cs.

moving a file from one project to another is an advanced use?

**Comment by SeanFeldman** [comment]
@SimonCropp yes, that means you're **not a beginner**.

Decision has to be made, if we remove the file and don't inject it, for upgrades, no problem. For new users, what that is going to look like? I don't have enough experience with the host to make that call.

**Comment by bording** [comment]
From my testing it looks like the overwriting behavior has been happening for a while, but it does seem undesirable to overwrite any existing `EndpointConfig.cs` files during an upgrade. I've pushed up #76 to address this.

Now if the file exists when you upgrade, you'll be prompted to overwrite it instead of it just happening silently.

**Comment by bording** [comment]
So, we either completely remove the `EndpointConfig.cs` file, or we can merge #76.

Once that's decided, it looks like the following samples should be updated/tested:
- https://github.com/Particular/docs.particular.net/tree/master/samples/hosting/nservicebus-host/Version_6
- https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostcustom/Version_6
- https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostdefault/Version_6
- https://github.com/Particular/docs.particular.net/tree/master/samples/logging/hostprofiles/Version_6

I believe those are all of the samples that use the host, but I might have missed one. @SeanFeldman and I were in the process of testing them when we realized we needing to update to a newer core unstable because the samples were all broken.

I also went and took a quick look at the Azure host, and it does not appear to have this problem, so we shouldn't need any changes there.

**Comment by andreasohlund** [comment]
#76 is merged , @weralabaj do U know the status of the docs?

**Comment by weralabaj** [comment]
I've updated PoA with things I've found.

**Comment by SeanFeldman** [comment]
Updated POA with a new doco PR that is pending a review.

**Comment by SeanFeldman** [comment]
PR merged.

**Comment by bording** [comment]
I've reviewed the doco PR and made a few changes. I believe it's ready to be merged now.
